# ================== General ==================
Id: BraveSoftware.BraveBrowser
Publisher: Brave Software, Inc.
Name: Brave Browser
Author: Brave Software, Inc.
Description: Secure, Fast & Private Web Browser with Adblocker
AppMoniker: Brave
Tags: Brave, Browser, Chrome, Chromium
#FileExtensions: http, https     # FileExtensions are not supported in this preview (5/24/2020)

# ================== License ==================
Homepage: https://brave.com
License: Mozilla Public License 2.0
LicenseUrl: https://github.com/brave/brave-browser/blob/master/LICENSE

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020)
Version: 1.10.97

InstallerType: exe
Installers:
  - Arch: x64
    Url: https://github.com/brave/brave-browser/releases/download/v1.10.97/BraveBrowserSilentSetup.exe
    Sha256: 1d069ddd70ac3c2cd500a422d3a90cc8543d78c9ecde4109efaceefb4128131a
    #Scope: user             # Scope is not supported in this preview (5/24/2020)
    
# ManifestVersion: 0.1.0
