Id: LINQPad.LINQPad
Version: 6.8
Name: LINQPad
Publisher: LINQPad
License: Copyright (c) LINQPad Pty Ltd
AppMoniker: linqpad
Tags: .net, sql
Description: The .NET Programmer’s Playground
Homepage: https://www.linqpad.net/
Installers:
  - Arch: Neutral
    Url: https://www.linqpad.net/GetFile.aspx?LINQPad6Setup.exe
    Sha256: 55ba7d499c6dc9e4e04e9b6fd3692e74c6623ebc7d9a7c18cf4a007ecf080ca4
    InstallerType: inno
    Switches:
      Silent: "/verysilent"
      SilentWithProgress: "/silent"