Id: AnyDeskSoftwareGmbH.AnyDesk
Version: 5.5.3
Name: AnyDesk
Publisher: AnyDesk Software GmbH
License: © 2020 AnyDesk Software GmbH - Made with passion in Stuttgart, Germany
Tags: remote-desktop
Description: AnyDesk is a German proprietary remote desktop tool distributed by AnyDesk Software GmbH.
Homepage: https://anydesk.com/
Installers:
  - Arch: x86
    Url: https://download.anydesk.com/AnyDesk.msi
    Sha256: D4A79DB5C21B2F0241057CC69DF78A0EA6B27888EDE66FC698791A19A6260E31
    InstallerType: msi
