Id: MasterPackager.MasterPackager
Version: 20.2.7457.0
Name: Master Packager
Publisher: Master Packager Ltd.
License: Copyright (c) 2020 Master Packager Ltd. All rights reserved.
LicenseUrl: https://www.masterpackager.com/eula
AppMoniker: masterpackager
Tags: Application Packaging, Master Packager, MSI, Windows Installer
Description: Master Packager is an application packaging tool to create and edit Microsoft Windows Installer (MSI) files and repackage other installation to MSI format.
Homepage: https://www.masterpackager.com/
Installers:
- Arch: x86
  Url: https://www.winget.it/dl/99effdd8b1a8ce73accc6aae1c59fccb4e8f6874a5df064cea2c527b1e269416/https%3A%2F%2Fwww.masterpackager.com%2Finstaller%2Fpublic%2Fstandard%2FMaster_Packager_Std_20.2.7457.0.msi
  Sha256: 75615508377B636177F458506B9EE6EE8635A37D0F9085EBAB4EE12BBDFCE467
  InstallerType: msi
  Scope: machine
MinOSVersion: 10.0.0.0
# Edited with MSIX Hero
