# ================== General ==================
Id: Lexikos.AutoHotkey
Publisher: Lexikos
Name: AutoHotkey
Author: Lexikos
Description: "AutoHotkey is a free, open-source scripting language for Windows that allows users to easily create small to complex scripts for all kinds of tasks such as: form fillers, auto-clicking, macros, etc."
AppMoniker: ahk
Tags: automation, hotkey, scripting, macro, keyboard, shortcut

# ================== License ==================
Homepage: https://www.autohotkey.com/
License: GPLv2
LicenseUrl: https://github.com/Lexikos/AutoHotkey_L/blob/master/license.txt

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020)
Version: 1.1.33.00

Switches:
      Custom: 
      Silent: /s
      SilentWithProgress: /s
      #Interactive:             # Interactive is not supported in this preview (5/24/2020)
      Language: en-US

InstallerType: exe
Installers:
  - Arch: Neutral
    Url: https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.33.00/AutoHotkey_1.1.33.00_setup.exe
    Sha256: 32e551b5638f905c976e1ae563597cbd53788660387b970bf77842dbb0d8fd36
    Scope: machine
    
# ManifestVersion: 0.1.0
