Id: Piriform.Defraggler
Publisher: Piriform Ltd
Name: Defraggler
Version: 2.22.995
AppMoniker: defraggler
Description: Boost performance by reassembling fragmented files
Homepage: https://www.ccleaner.com/defraggler
License: Copyright (c) 2005-2020 Piriform Ltd
InstallerType: exe
Installers:
  - Arch: x64
    Url: https://download.ccleaner.com/dfsetup222.exe
    Sha256: b53eb82d6a46c812171ca878b7342e1939a0afecc277b0b57c708eef8fc700de
    Switches:
          Silent: /S
          SilentWithProgress: /S