Id: Amazon.Kindle
Version: 1.25.52064
Name: Kindle
Publisher: Amazon
License: Copyright (c) Amazon.com, Inc. or its affiliates
LicenseUrl: https://www.amazon.com/gp/help/customer/display.html?nodeId=200699130
AppMoniker: kindle
Description: The Kindle app is available for most major smartphones, tablets and computers. That means with our free Kindle reading apps, you can buy a Kindle book once, and read it on any device with the Kindle app installed*. You can also read that same Kindle book on a Kindle device if you own one.
Homepage: https://www.amazon.com/kindle-dbs/fd/kcp
Tags: "reading, epub, reader, books, amazon, kindle"
Installers:
  - Arch: x86
    Url: https://s3.amazonaws.com/kindleforpc/52064/KindleForPC-installer-1.25.52064.exe
    Sha256: 314678A0A3B867BF412936ADAA67C6AB6D41C961F359A46F99C3AFA591702EF7
    InstallerType: nullsoft
