# ================== General ==================
Id: ProtonVPN.ProtonVPN
Publisher: ProtonVPN
Name: ProtonVPN
Author: ProtonVPN
Description: High-speed Swiss VPN that safeguards your privacy.
AppMoniker: protonvpn
Tags: vpn, privacy, security, private, network

# ================== License ==================
Homepage: https://protonvpn.com/
License: Copyright (c) Proton Technologies AG
LicenseUrl: https://protonvpn.com/terms-and-conditions

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020)
Version: 1.16.1

Switches:
      Custom: /norestart
      Silent: /qn
      SilentWithProgress: /qb
      #Interactive:             # Interactive is not supported in this preview (5/24/2020)
      Language: en-US

InstallerType: exe
Installers:
  - Arch: x86
    Url: https://protonvpn.com/download/ProtonVPN_win_v1.16.1.exe
    Sha256: a4d2cfca3209f21e50a02387439e90cb0dd595235560867059b178eee835d9e9
    Scope: machine
    
# ManifestVersion: 0.1.0
