# ================== General ==================
Id: TeamViewer.TeamViewer
Publisher: TeamViewer AG
Name: TeamViewer
Author: TeamViewer AG
Description: TeamViewer is a comprehensive, remote access, remote control and remote support solution that works with almost every desktop and mobile platform, including Windows, macOS, Android, and iOS. TeamViewer lets you remote in to computers or mobile devices located anywhere in the world and use them as though you were there.
AppMoniker: teamviewer
Tags: remote desktop, remote access, remote control, web conferencing

# ================== License ==================
Homepage: https://www.teamviewer.com/
License: Free For Private, Non-Commercial Use.
LicenseUrl: https://www.teamviewer.com/en/eula/

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020) 
Version: 15.7.7

InstallerType: Nullsoft
Installers:
  - Arch: x86
    Url: https://download.teamviewer.com/download/version_15x/TeamViewer_Setup.exe
    Sha256: bccfcb0cfd20b1d66682113faea2643cb9d6889336d863d3a4d5fdef0a6800c6
    Scope: machine
    
# ManifestVersion: 0.1.0
