Id: Adobe.AdobeAcrobatReaderDC
Version: 2020.009.20063
Name: Adobe Acrobat Reader DC
Publisher: Adobe
License: Copyright (c) Adobe
LicenseUrl: https://www.adobe.com/content/dam/cc/en/legal/licenses-terms/pdf/Reader-EULA-en_US-20181207.pdf
AppMoniker: adobereader
Description: The free global standard for reliably viewing, printing, signing, and commenting on PDF documents.
Homepage: https://acrobat.adobe.com/us/en/acrobat/pdf-reader.html
Installers:
  - Arch: x86
    Url: https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/1901020064/AcroRdrDC1901020064_MUI.exe
    Sha256: 81953F3CF426CBE9E6702D1AF7F727C59514C012D8D90BACFB012079C7DA6D23
    InstallerType: exe
    Switches:
      Silent: /sAll /rs /rps /l /re
      SilentWithProgress: /sPB /rs /rps /l /re
    Language: Multilingual
