Id: LutzRoeder.Netron
Version: 4.3.8
Name: Netron
Publisher: Lutz Roeder
AppMoniker: netron
Description: Visualizer for neural network, deep learning and machine learning models
License: Copyright (c) Lutz Roeder
Homepage: https://github.com/lutzroeder/netron
Installers:
  - Arch: x86
    InstallerType: nullsoft
    Url: https://github.com/lutzroeder/netron/releases/download/v4.3.8/Netron-Setup-4.3.8.exe
    Sha256: 51100B93143B0E92490BC447BF7C3B76E043611591C87E07BDFFD1F62E1D29C4
