Id: Intel.IntelDriverAndSupportAssistant
Publisher: Intel Corporation
Name: Intel® Driver & Support Assistant
AppMoniker: intel-dsa
Version: 20.5.20.3
License: Copyright (c) Intel Corporation
LicenseUrl: https://www.intel.com/content/www/us/en/legal/terms-of-use.html
Description: The Intel® Driver & Support Assistant enables you to scan computing devices for the latest drivers available from Intel.
Homepage: https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html
Tags: intel, driver, support, assistant
InstallerType: exe

Installers:
  - Arch: x86
    Url: https://downloadmirror.intel.com/28425/a08/Intel-Driver-and-Support-Assistant-Installer.exe
    Sha256: f2d9e1ff060b9f719907c6bf79b0cd15c9e2dadfe9412106ec16d3f74c77a893
    Switches:
      Silent: /S /NORESTART
      SilentWithProgress: /S /NORESTART
