Id: Ubisoft.Uplay
Name: Uplay
AppMoniker: uplay
Version: 109.0.7724.0
Publisher: Ubisoft
License: © Ubisoft Entertainment. All Rights Reserved.
LicenseUrl: https://legal.ubi.com/LegalInfoUbisoftEMEA
Description: Uplay service is a system that provides rewards and achievements for our players. This system also allows for games to use online content for statistics as well as the ability to share activities with friends.
Homepage: https://uplay.ubisoft.com
Tags: "games,uplay,store,purchase"
Installers:
  - Arch: Neutral
    Url: https://ubi.li/4vxt9
    Sha256: 799D100E2A0D9A051D5BDBC5CEC3359BC421D096A8F424F073FD5DA1C4E30263
    InstallerType: Nullsoft