Id: Google.Chrome
Name: Chrome
Publisher: Google
Version: 83.0.4103.61
Homepage: https://www.google.com/chrome/
InstallerType: MSI
AppMoniker: chrome
License: Google Chrome and Chrome OS Additional Terms of Service
LicenseUrl: https://www.google.com/chrome/terms/

# ======================= Installers  ==================


Installers:
  - Arch: x64
    Url: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise64.msi
    Sha256: 6c8cca05c33df2ed728ce900c54d9d0c6eab0a73a609b4ff087f6574085e73d6
    Language: en-US
