Id: HHDSoftware.FreeHexEditorNeo
Publisher: HHD Software Ltd.
Name: Free Hex Editor Neo
AppMoniker: hex-editor
Version: 6.44.01.6234
Description: 'Free: Freeware binary files editing tool'
Homepage: https://www.hhdsoftware.com/free-hex-editor
Tags: hex editor, binary file editor, hexeditor
License: Copyright (c) HHD Software Ltd. All rights reserved.
LicenseUrl: https://www.hhdsoftware.com/Official/software-licenses/HEXFREE
InstallerType: exe
Installers:
  - Arch: x64
    Url: http://www.hhdsoftware.com/Download/free-hex-editor-neo-6.44.01.6234.exe
    Sha256: dfc3c7cf57d07b0ed61a5101faf0d38d2a3b5c0054494fa381113bbacdfe261f
    Switches:
      Silent: -user -silent
      SilentWithProgress: -user -silent
